version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viewtime_app
    ports:
      - "8000:8000"   # FastAPI (direct access for debugging)
      - "8080:80"     # Nginx serving SPA + proxying API
    env_file:
      - .env.docker
    environment:
      # Fallbacks keep compose up even if env file is missing
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY:-}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL:-}
    volumes:
      - app_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles: [cache]

volumes:
  app_logs:
  redis_data:
